version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "main.py"]
    ports:
      - "8001:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - admin_mon_reseau

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
    networks:
      - admin_mon_reseau

  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33067:3306"
    networks:
      - admin_mon_reseau

networks:
  admin_mon_reseau:
    external: true
